hl.on("hyprland.start", function()
    hl.exec_cmd("hypridle")
    hl.exec_cmd("/usr/lib/hyprpolkitagent/hyprpolkitagent")
    hl.exec_cmd("clash-verge")
    hl.exec_cmd("fcitx5")
    hl.exec_cmd("rog-control-center")
    hl.exec_cmd("QT_QPA_PLATFORMTHEME=gtk3 qs -c noctalia-shell --no-duplicate")
    hl.exec_cmd("powerprofilesctl set power-saver")
end)
