# [Autostart]
exec-once = hypridle
exec-once = /usr/lib/hyprpolkitagent/hyprpolkitagent
exec-once = waybar
exec-once = mako
exec-once = nm-applet
exec-once = blueman-applet
exec-once = awww-daemon
exec-once = clash-verge
exec-once = fcitx5
exec-once = rog-control-center
exec-once = ~/.config/hypr/scripts/main-monitor-autoswitch.sh
exec-once = ~/.config/hypr/scripts/monitor-listener.sh
#exec-once = qs -c noctalia-shell --no-duplicate
exec-once = powerprofilesctl get power-saver # use power-saver profile by default
