# [Environment Variables]
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;xcb
env = CLUTTER_BACKEND,wayland
env = QT_QPA_PLATFORM,wayland;xcb
env = AQ_FORCE_LINEAR_BLIT,0

# Nvidia env
env = __GL_THREADED_OPTIMIZATIONS,1
env = __GL_SHADER_DISK_CACHE,1
env = __GL_SHADER_DISK_CACHE_PATH,/var/tmp/nvidia_shader_cache
env = NVIDIA_DRIVER_CAPABILITIES,all
env = __GL_SYNC_TO_VBLANK,1
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
