# [Monitors]
#monitor = eDP-1, 2560x1600@165, auto-right, 1.6
#monitor = eDP-1, disable
#monitor = DP-2, 1920x1080@165, 0x0, 1.0
monitor = ,highres@highrr,auto,auto
monitor = HDMI-A-1, 2560x1440@144, 0x0, 1.25, bitdepth, 10, cm, srgb
